users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email


class LoginForm(FlaskForm):

    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegisterForm(FlaskForm):

    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_pw = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')


class ResetForm(FlaskForm):

    email = StringField('Email', validators=[Email()])
    submit = SubmitField('Submit')


class UpdateForm(FlaskForm):

    password = PasswordField('Current Password', validators=[DataRequired()])
    new_pw = PasswordField('New Password', validators=[DataRequired()])
    confirm_pw = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Submit')


class AccountForm(FlaskForm):

    email = StringField('Email')
    current_pw = PasswordField('Current Password')
    new_pw = PasswordField('New Password')
    confirm_pw = PasswordField('Confirm Password')
    submit = SubmitField('Submit')


class DeleteForm(FlaskForm):

    email = StringField(
        'Enter your email to confirm',
        validators=[DataRequired()])
    submit = SubmitField('Delete')

users/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for)
from flask_login import current_user, login_user, logout_user
from werkzeug.wrappers import Response

from .forms import (
    AccountForm,
    DeleteForm,
    LoginForm,
    RegisterForm,
    ResetForm,
    UpdateForm)
from utils import admin_auth, is_staging, make_api_request

user_blueprint = Blueprint(
    'users',
    __name__,
    template_folder='templates')


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = LoginForm()
    login_args = {'title': 'Login', 'form': form}
    if form.validate_on_submit():
        res = make_api_request('post', 'users/login', data={
            'email': form.email.data,
            'password': form.password.data})
        if res.status_code == 200:
            login_user(res.json().get('user'))
            flash(res.message, 'message')
            next = request.args.get('next')
            if next is None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)
        else:
            flash(res.message, 'warning')
            return render_template('login.html', **login_args)
    return render_template('login.html', **login_args)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = RegisterForm()
    register_args = {'title': 'Register', 'form': form}
    if form.validate_on_submit():
        res = make_api_request('post', 'users/register', data={
            'email': form.email.data,
            'password': form.password.data,
            'confirm_pw': form.confirm_pw.data})
        if res.status_code == 200:
            flash(res.message, 'message')
            return redirect(url_for('users.login'))
        else:
            flash(res.message, 'warning')
            return render_template('register.html', **register_args)
    return render_template('register.html', **register_args)


@user_blueprint.route('/reset', methods=['GET', 'POST'])
def reset() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = ResetForm()
    reset_args = {'title': 'Reset', 'form': form}
    if form.validate_on_submit():
        res = make_api_request('post', 'users/reset', data={
            'email': form.email.data})
        if res.status_code == 200:
            flash(res.message, 'message')
            return redirect(url_for('users.update'))
        else:
            flash(res.message, 'warning')
            return render_template('reset.html', **reset_args)
    return render_template('reset_pw.html', **reset_args)


@user_blueprint.route('/update', methods=['GET', 'POST'])
def update() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = UpdateForm()
    update_args = {'title': 'Update', 'form': form}
    if form.validate_on_submit():
        res = make_api_request('put', 'users/update', data={
            'email': current_user.email,
            'password': form.password.data,
            'new_pw': form.new_pw.data,
            'confirm_pw': form.confirm_pw.data})
        if res.status_code == 200:
            flash(res.message, 'message')
            return redirect(url_for('users.login'))
        else:
            flash(res.message, 'warning')
            return render_template('update.html', **update_args)
    return render_template('update.html', **update_args)


@user_blueprint.route('/account', methods=['GET', 'POST'])
def account() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = AccountForm()
    del_form = DeleteForm()
    if form.validate_on_submit():
        res = make_api_request('put', 'users/account', data={
            'email': form.email.data,
            'current_pw': form.current_pw.data,
            'new_pw': form.new_pw.data,
            'confirm_pw': form.confirm_pw.data,
        })
        if res.status_code == 200:
            flash(res.message, 'message')
        else:
            flash(res.message, 'warning')
    if del_form.validate_on_submit():
        email = del_form.email.data,
        if email != current_user.email:
            flash('Invalid email', 'warning')
        else:
            res = make_api_request('delete', 'users/delete', data={
                'email': email})
            if res.status_code == 200:
                flash(res.message, 'message')
                return redirect(url_for('users.login'))
            else:
                flash(res.message, 'warning')
    return render_template('account.html', form=form, del_form=del_form)


@user_blueprint.route('/logout', methods=['POST'])
def logout() -> Response:
    logout_user()
    flash('Logged out', 'message')
    return redirect(url_for('users.login'))

users/templates/account.html
{% extends 'base.html' %}

{% block body %}

<div class="api-form-container">
    <header class="main-header">
        <div class="app-name-container invisible">
            <p class="app-name">Scramble API</p>
        </div>
        <div class="menu-container" onclick="toggleMenu(this)">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>
        <div class="menu-options-container invisible">
            <a class="menu-option" href="{{url_for('core.index')}}" onclick="clearMenu()">Home</a>
            <a class="menu-option" href="{{url_for('users.account')}}" onclick="clearMenu()">My Account</a>
            <form class="logout-form" action="{{url_for('users.logout')}}" method="post">
                <input class="logout-btn" type="submit" value="Logout">
            </form>
        </div> 
    </header>

    <div class="account-data-container">
        <h1>My Account</h1>
        <form class="form" action="{{url_for('users.account')}}" method="POST">
            {{ form.hidden_tag() }}
            {{ form.email.label(class='form-label') }} {{ form.email(class='form-input') }}
            <p class="update-pw-label">Change your password</p>
            {{ form.current_pw.label(class='form-label') }} {{ form.current_pw(class='form-input') }}
            {{ form.new_pw.label(class='form-label') }} {{ form.new_pw(class='form-input') }}
            {{ form.confirm_pw.label(class='form-label') }} {{ form.confirm_pw(class='form-input') }}
            {{ form.submit(class="submit-btn") }}
        </form>
        <div class="delete-account-option-container">
            <h2>Delete your account?</h2>
            <p class="delete-account-warning">
                This action will delete all the data held against your account including your user ID, 
                email address, login data, and password history. This action cannot be undone so if you 
                want to use the service again you will need to re-register, your previous email will be 
                valid if you wish to sign back up. In accordance with GDPR regulations you are free to 
                remove your data from our system at any time.
            </p>
            <button class="delete-account-btn" onclick="showDeleteModal()">Delete Account</button>
        </div>
    </div>

    <div id="block-screen"></div>

    <div class="delete-account-modal invisible" id="delete-modal">
        <form action="{{url_for('users.account')}}" method="POST">
            <h2 class="delete-account-header">Confirm Deletion</h2>
            {{ del_form.hidden_tag() }}
            {{ del_form.email.label(class='form-label') }}
            <br />
            {{ del_form.email(class='form-input', id='delete-account-input') }}
            <div class="delete-form-btn-container">
                {{ del_form.submit(class="delete-btn") }}
                <button class="cancel-delete-btn" onclick="hideDeleteModal()">Cancel</button>
            </div>
        </form>
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-text-container">
                <p class="footer-text">Scramble API created by sedex</p>
                <p class="footer-text">Follow the project or get involved on <a class="footer-link" href="https://github.com/sedexdev">Github</a></p>
            </div>
        </div>
    </footer>
</div>

{% endblock %}

users/templates/login.html
{% extends 'base.html' %}

{% block body %}

<div class="form-container">
    <h1 class="form-heading">Login</h1>
    <form class="form" action="{{url_for('users.login')}}" method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label(class='form-label') }} 
        {{ form.email(class='form-input', id='email') }}
        {{ form.password.label(class='form-label') }}
        {{ form.password(class='form-input', id='password') }}
        {{ form.submit(class='submit-btn') }}
    </form>
    <p class="user-link">Haven't registered? <a href="{{url_for('users.register')}}">Register</a></p>
    <p class="user-link">Forgotten your password? Click <a href="{{url_for('users.reset')}}">here</a></p>
</div> 

{% endblock %}

users/templates/register.html
{% extends 'base.html' %}

{% block body %}

<div class="form-container">
    <h1 class="form-heading">Register</h1>
    <form class="form" action="{{url_for('users.register')}}" method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label(class='form-label') }} 
        {{ form.email(class='form-input', id='email') }}
        {{ form.password.label(class='form-label') }}
        {{ form.password(class='form-input', id='password') }}
        {{ form.confirm_pw.label(class='form-label') }}
        {{ form.confirm_pw(class='form-input', id='confirm_pw') }}
        {{ form.submit(class='submit-btn') }}
    </form>
    <p class="user-link">Already registered? <a href="{{url_for('users.login')}}">Login</a></p>
</div> 

{% endblock %}

users/templates/reset_pw.html
{% extends 'base.html' %}

{% block body %}

<div class="form-container">
    <h1 class="form-heading">Reset</h1>
    <form class="form" action="{{url_for('users.reset')}}" method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label(class='form-label') }} 
        {{ form.email(class='form-input', id='email') }}
        {{ form.submit(class='submit-btn') }}
    </form>
    <p class="user-link"><a href="{{url_for('users.login')}}">Back</a></p>
</div> 

{% endblock %}

users/templates/update.html
{% extends 'base.html' %}

{% block body %}

<div class="form-container">
    <h1 class="form-heading">Update Password</h1>
    <form class="form" action="{{url_for('users.update')}}" method="POST">
        {{ form.hidden_tag() }}
        {{ form.password.label(class='form-label') }} 
        {{ form.password(class='form-input', id='password') }}
        {{ form.new_pw.label(class='form-label') }}
        {{ form.new_pw(class='form-input', id='new_pw') }}
        {{ form.confirm_pw.label(class='form-label') }}
        {{ form.confirm_pw(class='form-input', id='confirm_pw') }}
        {{ form.submit(class='submit-btn') }}
    </form>
</div> 

{% endblock %}