core/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import IntegerField, RadioField, SubmitField, TextAreaField


class APIForm(FlaskForm):

    shift_value = IntegerField('Shift Value*')

    random_shift = RadioField(
        'Use Random Shift Value?*',
        choices=[
            ('random', 'Select to use a random shift value')
        ]
    )

    encryption = RadioField(
        'Encryption Type',
        choices=[
            ('rsa', 'RSA'),
            ('aes', 'AES')
        ])

    hashing = RadioField(
        'Hashing Algorithm',
        choices=[
            ('md5', 'MD5*'),
            ('blake2b', 'BLAKE2b'),
            ('blake2s', 'BLAKE2s'),
            ('pbkdf2_hmac', 'PBKDF2-HMAC'),
            ('sha1', 'SHA-1*'),
            ('sha224', 'SHA-224'),
            ('sha256', 'SHA-256'),
            ('sha384', 'SHA-384'),
            ('sha512', 'SHA-512'),
            ('sha3_224', 'SHA3-224'),
            ('sha3_256', 'SHA3-256'),
            ('sha3_384', 'SHA3-384'),
            ('sha3_512', 'SHA3-512'),
            ('shake_128', 'SHAKE-128'),
            ('shake_256', 'SHAKE-256'),
        ]
    )

    text = TextAreaField('Paste Plaintext')

    file_upload = FileField(
        'Upload file',
        validators=[
            FileAllowed(['.txt', '.pdf', '.docx'], 'Text files only!')])

    submit = SubmitField('Submit')

core/views.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    url_for)
from werkzeug.wrappers import Response

from utils import admin_auth, is_staging, make_api_request
from .forms import APIForm

core_blueprint = Blueprint(
    'core',
    __name__,
    template_folder='templates')


@core_blueprint.route('/', methods=['GET', 'POST'])
def index() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    return render_template('index.html')


@core_blueprint.route('/substitution', methods=['GET', 'POST'])
def substitution() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = APIForm()
    index_args = {'title': 'Scramble API', 'form': form}
    if form.validate_on_submit():
        res = make_api_request('post', 'substitution', data={
            'shift_value': form.shift_value.data,
            'random_shift': form.random_shift.data,
            'text': form.text.data,
            'file': form.file_upload.data
        })
        if res.status_code == 200:
            results = res.json()
            flash(results['message'], 'message')
            return render_template('results.html', results=results)
        else:
            flash(res.message, 'warning')
            return render_template('substitution.html', **index_args)
    return render_template('substitution.html', **index_args)


@core_blueprint.route('/hashing', methods=['GET', 'POST'])
def hashing() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = APIForm()
    index_args = {'title': 'Scramble API', 'form': form}
    if form.validate_on_submit():
        res = make_api_request('post', 'hashing', data={
            'hashing': form.hashing.data,
            'text': form.text.data,
            'file': form.file_upload.data
        })
        if res.status_code == 200:
            results = res.json()
            flash(results['message'], 'message')
            return render_template('results.html', results=results)
        else:
            flash(res.message, 'warning')
            return render_template('hash.html', **index_args)
    return render_template('hash.html', **index_args)


@core_blueprint.route('/encryption', methods=['GET', 'POST'])
def encryption() -> Response:
    if is_staging() and not admin_auth():
        return redirect(url_for('admin.login_admin'))
    form = APIForm()
    index_args = {'title': 'Scramble API', 'form': form}
    if form.validate_on_submit():
        res = make_api_request('post', 'encryption', data={
            'encryption': form.encryption.data,
            'text': form.text.data,
            'file': form.file_upload.data
        })
        if res.status_code == 200:
            results = res.json()
            flash(results['message'], 'message')
            return render_template('results.html', results=results)
        else:
            flash(res.message, 'warning')
            return render_template('encrypt.html', **index_args)
    return render_template('encrypt.html', **index_args)


@core_blueprint.route('/results')
def results():
    return render_template('results.html')

core/templates/encrypt.html
{% extends 'base.html' %}

{% block body %}

<div>
    <div class="api-form-container">
        <header class="main-header">
            <div class="app-name-container invisible">
                <p class="app-name">Scramble API</p>
            </div>
            <div class="menu-container" onclick="toggleMenu(this)">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
            <div class="menu-options-container invisible">
                <a class="menu-option" href="{{url_for('core.index')}}" onclick="clearMenu()">Home</a>
                <a class="menu-option" href="{{url_for('users.account')}}" onclick="clearMenu()">My Account</a>
                <form class="logout-form" action="{{url_for('users.logout')}}" method="post">
                    <input class="logout-btn" type="submit" value="Logout">
                </form>
            </div> 
        </header>
    
        <div class="form-container">
            <h1 class="core-heading invisible">Scramble API</h1>
            <form class="form" action="{{url_for('core.encryption')}}" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                {{ form.encryption.label(class="form-label", id="encryption-label") }}
                {{ form.encryption(class="form-radio") }}
                {{ form.text.label(class='form-label', id="text-label") }}
                {{ form.text(class='form-input-ta') }}
                <p class="or-separator">or</p>
                {{ form.file_upload.label(class='form-label', id="file-label") }}
                {{ form.file_upload(class='form-input') }}
                {{ form.submit(class='submit-btn') }}
                <p class="insecure-warning">* algorithm is considered insecure</p>
            </form>
            <p>
                <a href="{{ url_for('core.hashing') }}">Hash instead</a>
                |
                <a href="{{ url_for('core.index') }}">Home</a>
            </p>
        </div> 
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-text-container">
                <p class="footer-text">Scramble API created by sedex</p>
                <p class="footer-text">Follow the project or get involved on <a class="footer-link" href="https://github.com/sedexdev">Github</a></p>
            </div>
        </div>
    </footer>
</div>

{% endblock %}

core/templates/hash.html
{% extends 'base.html' %}

{% block body %}

<div>
    <div class="api-form-container">
        <header class="main-header">
            <div class="app-name-container invisible">
                <p class="app-name">Scramble API</p>
            </div>
            <div class="menu-container" onclick="toggleMenu(this)">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
            <div class="menu-options-container invisible">
                <a class="menu-option" href="{{url_for('core.index')}}" onclick="clearMenu()">Home</a>
                <a class="menu-option" href="{{url_for('users.account')}}" onclick="clearMenu()">My Account</a>
                <form class="logout-form" action="{{url_for('users.logout')}}" method="post">
                    <input class="logout-btn" type="submit" value="Logout">
                </form>
            </div> 
        </header>
    
        <div class="form-container">
            <h1 class="core-heading invisible">Scramble API</h1>
            <form class="form" action="{{url_for('core.hashing')}}" method="POST" enctype = "multipart/form-data">
                {{ form.hidden_tag() }}
                {{ form.hashing.label(class="form-label", id="hashing-label") }}
                {{ form.hashing(class="form-radio") }}
                {{ form.text.label(class='form-label', id="text-label") }}
                {{ form.text(class='form-input-ta') }}
                <p class="or-separator">or</p>
                {{ form.file_upload.label(class='form-label', id="file-label") }}
                {{ form.file_upload(class='form-input') }}
                {{ form.submit(class='submit-btn') }}
                <p class="insecure-warning">* algorithm is considered insecure</p>
            </form>
            <p><a href="{{ url_for('core.index') }}">Home</a></p>
        </div> 
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-text-container">
                <p class="footer-text">Scramble API created by sedex</p>
                <p class="footer-text">Follow the project or get involved on <a class="footer-link" href="https://github.com/sedexdev">Github</a></p>
            </div>
        </div>
    </footer>
</div>

{% endblock %}

core/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div class="api-form-container">
    <header class="main-header">
        <div class="app-name-container invisible">
            <p class="app-name">Scramble API</p>
        </div>
        <div class="menu-container" onclick="toggleMenu(this)">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>
        <div class="menu-options-container invisible">
            <a class="menu-option" href="{{url_for('core.index')}}" onclick="clearMenu()">Home</a>
            <a class="menu-option" href="{{url_for('users.account')}}" onclick="clearMenu()">My Account</a>
            <form class="logout-form" action="{{url_for('users.logout')}}" method="post">
                <input class="logout-btn" type="submit" value="Logout">
            </form>
        </div> 
    </header>

    <div class="service-options-outer-container">
        <p>Service options</p>
        <div class="service-options-container">
            <a class="service-options-link" id="subs-link" href="{{ url_for('core.substitution') }}">Substitution</a>
            <a class="service-options-link" id="hash-link" href="{{ url_for('core.hashing') }}">Hashing</a>
            <a class="service-options-link" id="encrypt-link" href="{{ url_for('core.encryption') }}">Encryption</a>
        </div>
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-text-container">
                <p class="footer-text">Scramble API created by sedex</p>
                <p class="footer-text">Follow the project or get involved on <a class="footer-link" href="https://github.com/sedexdev">Github</a></p>
            </div>
        </div>
    </footer>
</div>

{% endblock %}

core/templates/results.html
{% extends 'base.html' %}

{% block body %}

<div class="api-form-container">
    <header class="main-header">
        <div class="app-name-container invisible">
            <p class="app-name">Scramble API</p>
        </div>
        <div class="menu-container" onclick="toggleMenu(this)">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>
        <div class="menu-options-container invisible">
            <a class="menu-option" href="{{url_for('core.index')}}" onclick="clearMenu()">Home</a>
            <a class="menu-option" href="{{url_for('users.account')}}" onclick="clearMenu()">My Account</a>
            <form class="logout-form" action="{{url_for('users.logout')}}" method="post">
                <input class="logout-btn" type="submit" value="Logout">
            </form>
        </div> 
    </header>

    <div class="results-data-container">
        <h1>API Results</h1>  
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-text-container">
                <p class="footer-text">Scramble API created by sedex</p>
                <p class="footer-text">Follow the project or get involved on <a class="footer-link" href="https://github.com/sedexdev">Github</a></p>
            </div>
        </div>
    </footer>
</div>

{% endblock %}

core/templates/substitution.html
{% extends 'base.html' %}

{% block body %}

<div>
    <div class="api-form-container">
        <header class="main-header">
            <div class="app-name-container invisible">
                <p class="app-name">Scramble API</p>
            </div>
            <div class="menu-container" onclick="toggleMenu(this)">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
            <div class="menu-options-container invisible">
                <a class="menu-option" href="{{url_for('core.index')}}" onclick="clearMenu()">Home</a>
                <a class="menu-option" href="{{url_for('users.account')}}" onclick="clearMenu()">My Account</a>
                <form class="logout-form" action="{{url_for('users.logout')}}" method="post">
                    <input class="logout-btn" type="submit" value="Logout">
                </form>
            </div> 
        </header>
    
        <div class="form-container">
            <h1 class="core-heading invisible">Scramble API</h1>
            <form class="form" action="{{url_for('core.substitution')}}" method="POST" enctype = "multipart/form-data">
                {{ form.hidden_tag() }}
                {{ form.shift_value.label(class="form-label") }}
                {{ form.shift_value(class="form-input") }}
                {{ form.random_shift.label(class="form-label") }}
                {{ form.random_shift(class="form-radio") }}
                {{ form.text.label(class='form-label', id="text-label") }}
                {{ form.text(class='form-input-ta') }}
                <p class="or-separator">or</p>
                {{ form.file_upload.label(class='form-label', id="file-label") }}
                {{ form.file_upload(class='form-input') }}
                {{ form.submit(class='submit-btn') }}
                <p class="insecure-warning">* punctuation will be preserved</p>
            </form>
            <p><a href="{{ url_for('core.index') }}">Home</a></p>
        </div> 
    </div>

    <footer>
        <div class="footer-container">
            <div class="footer-text-container">
                <p class="footer-text">Scramble API created by sedex</p>
                <p class="footer-text">Follow the project or get involved on <a class="footer-link" href="https://github.com/sedexdev">Github</a></p>
            </div>
        </div>
    </footer>
</div>

{% endblock %}